export interface Job {
  id: string;
  title: string;
  department: string;
  location: string;
  type: "Full-time" | "Contract" | "Part-time";
  salary: string;
  description: string;
  responsibilities: string[];
  requirements: string[];
  benefits: string[];
  skills: string[];
}

export const jobs: Job[] = [
  {
    id: "senior-devops-engineer",
    title: "Senior DevOps Engineer",
    department: "Infrastructure",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$180k - $240k",
    description:
      "Join our infrastructure team to build and maintain scalable cloud systems. You'll work with cutting-edge technologies and lead infrastructure initiatives across the company.",
    responsibilities: [
      "Design and implement CI/CD pipelines using Docker, Kubernetes, and modern DevOps tools",
      "Manage cloud infrastructure on AWS and GCP with infrastructure-as-code (Terraform)",
      "Implement monitoring, logging, and alerting systems for 99.99% uptime",
      "Mentor junior engineers and conduct code reviews",
      "Collaborate with product teams to ensure scalable infrastructure",
      "Manage database replication and disaster recovery procedures",
    ],
    requirements: [
      "8+ years of experience in DevOps or infrastructure engineering",
      "Expert knowledge of Kubernetes, Docker, and container orchestration",
      "Strong experience with AWS or GCP",
      "Proficiency in infrastructure-as-code tools (Terraform, CloudFormation)",
      "Experience with CI/CD systems (Jenkins, GitLab CI, GitHub Actions)",
      "Strong understanding of networking, security, and system administration",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Comprehensive health, dental, and vision insurance",
      "401(k) matching up to 6%",
      "Unlimited PTO and flexible work arrangements",
      "Professional development budget ($5k/year)",
      "Home office setup allowance",
      "MacBook Pro and equipment of your choice",
    ],
    skills: ["Kubernetes", "AWS", "Terraform", "Docker", "CI/CD", "Linux", "Python", "Go"],
  },
  {
    id: "senior-full-stack-engineer",
    title: "Senior Full Stack Engineer",
    department: "Engineering",
    location: "New York, NY",
    type: "Full-time",
    salary: "$170k - $230k",
    description:
      "Build scalable web applications using modern tech stacks. You'll own features end-to-end, from database design to user interfaces, working with TypeScript, React, and Node.js.",
    responsibilities: [
      "Develop and maintain scalable web applications using React and Node.js",
      "Design and implement RESTful APIs and GraphQL services",
      "Collaborate with product and design teams to implement new features",
      "Optimize application performance and database queries",
      "Write comprehensive tests and improve code quality",
      "Participate in architectural discussions and technical planning",
      "Review pull requests and mentor junior developers",
    ],
    requirements: [
      "7+ years of full-stack web development experience",
      "Expert knowledge of TypeScript, React, and Node.js",
      "Experience with relational databases (PostgreSQL, MySQL)",
      "Familiarity with modern development tools and frameworks",
      "Experience with version control (Git) and agile methodologies",
      "Understanding of RESTful API design and GraphQL",
      "Strong problem-solving and communication skills",
    ],
    benefits: [
      "Competitive salary and stock options",
      "Comprehensive health, dental, and vision coverage",
      "401(k) with 6% company match",
      "Unlimited paid time off",
      "Learning and development budget",
      "Remote work options available",
      "Collaborative office environment in Manhattan",
    ],
    skills: ["TypeScript", "React", "Node.js", "PostgreSQL", "GraphQL", "AWS", "Testing"],
  },
  {
    id: "data-scientist",
    title: "Data Scientist",
    department: "Data & Analytics",
    location: "Boston, MA",
    type: "Full-time",
    salary: "$150k - $210k",
    description:
      "Help us leverage data to drive business decisions. Work with large-scale datasets, build predictive models, and create actionable insights using modern ML techniques.",
    responsibilities: [
      "Develop machine learning models for predictive analytics and recommendations",
      "Design and implement data pipelines and ETL processes",
      "Analyze large datasets using Python, R, and SQL",
      "Collaborate with product teams to understand business requirements",
      "Create data visualizations and dashboards for stakeholders",
      "Deploy and monitor ML models in production",
      "Stay updated with latest ML research and best practices",
    ],
    requirements: [
      "5+ years of experience in data science or machine learning",
      "Proficiency in Python, R, or Scala",
      "Advanced SQL skills for complex data analysis",
      "Experience with machine learning frameworks (TensorFlow, PyTorch, scikit-learn)",
      "Knowledge of statistical methods and experimental design",
      "Familiarity with big data tools (Spark, Hadoop)",
      "Strong communication skills for presenting findings",
    ],
    benefits: [
      "Excellent salary and bonus structure",
      "Comprehensive benefits package",
      "Stock options and 401(k) matching",
      "Unlimited PTO",
      "Professional conference attendance",
      "GPU workstations for model development",
      "Collaborative research environment",
    ],
    skills: [
      "Python",
      "Machine Learning",
      "SQL",
      "TensorFlow",
      "PyTorch",
      "Statistics",
      "Data Visualization",
    ],
  },
  {
    id: "product-manager",
    title: "Senior Product Manager",
    department: "Product",
    location: "Austin, TX",
    type: "Full-time",
    salary: "$160k - $220k",
    description:
      "Own and drive the vision for our core product features. Work cross-functionally with engineering, design, and marketing teams to deliver impactful solutions.",
    responsibilities: [
      "Define product strategy and roadmap for assigned product area",
      "Gather and analyze market research and user feedback",
      "Write clear requirements and user stories for engineering teams",
      "Collaborate with designers on user experience and interface design",
      "Track and communicate product metrics and KPIs",
      "Conduct user interviews and usability testing",
      "Manage product priorities and resource allocation",
    ],
    requirements: [
      "5+ years of product management experience",
      "Experience launching successful products or features",
      "Strong analytical and quantitative skills",
      "Excellent written and verbal communication",
      "Experience with data analysis and A/B testing",
      "Understanding of SaaS business models",
      "Familiarity with Agile/Scrum methodologies",
    ],
    benefits: [
      "Competitive salary and performance bonus",
      "Equity package",
      "Comprehensive health coverage",
      "401(k) with matching",
      "Flexible work arrangements",
      "Learning budget for courses and conferences",
      "Wellness programs and gym stipend",
    ],
    skills: [
      "Product Strategy",
      "Analytics",
      "User Research",
      "Roadmapping",
      "SQL",
      "A/B Testing",
      "Agile",
    ],
  },
  {
    id: "ui-ux-designer",
    title: "UI/UX Designer",
    department: "Design",
    location: "Seattle, WA",
    type: "Full-time",
    salary: "$130k - $180k",
    description:
      "Create beautiful and intuitive user experiences for our web and mobile applications. Work with a talented design team to shape how millions of users interact with our products.",
    responsibilities: [
      "Design user interfaces for web and mobile applications",
      "Conduct user research and usability testing",
      "Create wireframes, prototypes, and high-fidelity mockups",
      "Maintain and evolve the design system and component library",
      "Collaborate with product managers and engineers",
      "Develop design specifications and style guides",
      "Stay updated with design trends and best practices",
    ],
    requirements: [
      "5+ years of UI/UX design experience",
      "Proficiency in design tools (Figma, Adobe XD, Sketch)",
      "Strong portfolio demonstrating design process",
      "Understanding of design systems and component libraries",
      "Experience with responsive design and mobile-first approach",
      "Knowledge of web accessibility (WCAG) standards",
      "Excellent communication and collaboration skills",
    ],
    benefits: [
      "Competitive salary and annual bonus",
      "Creative work environment",
      "Stock options",
      "Health, dental, and vision insurance",
      "401(k) matching",
      "Unlimited PTO",
      "Design tools and equipment budget",
    ],
    skills: [
      "Figma",
      "User Research",
      "Prototyping",
      "Design Systems",
      "Accessibility",
      "Typography",
      "Color Theory",
    ],
  },
  {
    id: "backend-engineer",
    title: "Backend Engineer",
    department: "Engineering",
    location: "Remote",
    type: "Full-time",
    salary: "$140k - $190k",
    description:
      "Build and optimize backend services that power our platform. Work with scalable architectures and modern technologies to handle millions of requests daily.",
    responsibilities: [
      "Develop and maintain backend APIs and services using Node.js or Go",
      "Design and optimize database schemas for performance",
      "Implement caching strategies and optimize query performance",
      "Ensure code quality through testing and code reviews",
      "Collaborate with frontend teams on API contracts",
      "Monitor and debug production issues",
      "Contribute to architecture discussions and technical planning",
    ],
    requirements: [
      "4+ years of backend development experience",
      "Strong proficiency in Node.js, Go, Java, or Python",
      "Experience with SQL and NoSQL databases",
      "Knowledge of API design and RESTful principles",
      "Familiarity with containerization (Docker, Kubernetes)",
      "Understanding of microservices architecture",
      "Strong debugging and problem-solving skills",
    ],
    benefits: [
      "Competitive salary",
      "Stock options",
      "Comprehensive health insurance",
      "401(k) with 6% match",
      "Fully remote work opportunity",
      "Home office setup allowance",
      "Learning and development budget",
    ],
    skills: ["Node.js", "Go", "PostgreSQL", "Docker", "Microservices", "API Design", "Testing"],
  },
  {
    id: "security-engineer",
    title: "Security Engineer",
    department: "Security",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$160k - $220k",
    description:
      "Lead security initiatives and protect our platform. Work on vulnerability assessments, security architecture, and incident response to keep our users safe.",
    responsibilities: [
      "Conduct security assessments and vulnerability testing",
      "Design and implement security controls and best practices",
      "Develop security training and awareness programs",
      "Investigate and respond to security incidents",
      "Maintain compliance with security standards (SOC2, HIPAA)",
      "Review code for security vulnerabilities",
      "Collaborate with teams on security requirements",
    ],
    requirements: [
      "6+ years of cybersecurity or application security experience",
      "Knowledge of OWASP Top 10 and common vulnerabilities",
      "Proficiency with security tools and vulnerability scanners",
      "Understanding of cryptography and authentication methods",
      "Experience with compliance frameworks and standards",
      "Knowledge of cloud security best practices",
      "Strong communication and documentation skills",
    ],
    benefits: [
      "Competitive salary and bonus",
      "Equity package",
      "Comprehensive health coverage",
      "401(k) with matching",
      "Security certification reimbursement",
      "Professional conference budget",
      "Home office equipment allowance",
    ],
    skills: [
      "Application Security",
      "Penetration Testing",
      "OWASP",
      "Cryptography",
      "Compliance",
      "Python",
      "Linux",
    ],
  },
];
